base_de_contacts/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :contacts

  root 'welcome#index'
end

base_de_contacts/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

base_de_contacts/app/models/contact.rb
class Contact < ApplicationRecord
  validates :firstname, :lastname, presence: true, length: { minimum: 2 }
  validates :email, presence: true
  validates :tel, presence: true, numericality: true, length: { minimum: 9, maximum: 15 }


end

base_de_contacts/app/models/person.rb
class Person < ApplicationRecord
  validates :firstname, :lastname, presence: true, length: { minimum: 5 }
  validates :email, presence: true
end

base_de_contacts/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

base_de_contacts/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def edit
    @contact = Contact.find(params[:id])
  end
  def index
    @contacts = Contact.all
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to @contact
    else
      render 'new'
    end
  end

  def update
    @contact = Contact.find(params[:id])

    if @contact.update(contact_params)
      redirect_to @contact
    else
      render 'edit'
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    redirect_to contacts_path
  end

  private
    def contact_params
      params.require(:contact).permit(:firstname, :lastname, :email, :tel, :bio)
    end
end

base_de_contacts/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

base_de_contacts/app/helpers/application_helper.rb
module ApplicationHelper
end

base_de_contacts/app/helpers/contacts_helper.rb
module ContactsHelper
end

base_de_contacts/app/helpers/persons_helper.rb
module PersonsHelper
end

base_de_contacts/app/helpers/welcome_helper.rb
module WelcomeHelper
end

base_de_contacts/app/views/contacts/_form.html.erb
<%= form_with model: @contact, local: true do |form| %>

  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@contact.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @contact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :firstname %><br>
    <%= form.text_field :firstname %>
  </p>

  <p>
    <%= form.label :lastname %><br>
    <%= form.text_field :lastname %>
  </p>

  <p>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
  </p>

  <p>
    <%= form.label :tel %><br>
    <%= form.telephone_field :tel %>
  </p>

  <p>
    <%= form.label :bio %><br>
    <%= form.text_area :bio %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

base_de_contacts/app/views/contacts/edit.html.erb
<h1>Edit Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

base_de_contacts/app/views/contacts/index.html.erb
<h1>Listing contact</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th colspan="2"></th>
  </tr>

  <% @contacts.each do |contact| %>
    <tr>
      <td><%= contact.firstname %></td> <td><%= contact.lastname %></td>
      <td><%= link_to 'Show', contact_path(contact) %></td>
      <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
      <td><%= link_to 'Destroy', contact_path(contact),
              method: :delete,
              data: {confirm: 'Are you Ok ? To delete your contact ?'} %></td>
    </tr>
  <% end %>
</table>

<p>
  <%= link_to 'New contact', new_contact_path %>
</p>

<p>
  <%= link_to 'Back', contacts_path %>
</p>

base_de_contacts/app/views/contacts/new.html.erb
<h1> New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

base_de_contacts/app/views/contacts/show.html.erb
<h1>Show contact</h1>

<p>
  <strong>First name:</strong> <%= @contact.firstname %>
</p>

<p>
  <strong>Last name:</strong> <%= @contact.lastname %>
</p>

<p>
  <strong>Email:</strong> <%= @contact.email %>
</p>

<p>
  <strong>Telephone:</strong> <%= @contact.tel %>
</p>
<p>
  <strong>Bio:</strong>
  <%= @contact.bio %>
</p>

<p>
  <%= link_to 'Edit', edit_contact_path(@contact) %> |
  <%= link_to 'Back', contacts_path %>
</p>

base_de_contacts/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BaseDeContacts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

base_de_contacts/app/views/persons/edit.html.erb
<h1>Edit Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', persons_path %>

base_de_contacts/app/views/persons/new.html.erb
<h1> New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', persons_path %>

base_de_contacts/app/views/welcome/index.html.erb
<h1>Base de Contacts</h1>
<%= link_to 'contacts', controller: 'persons'%>